"use client";
import { ExternalLink, Filter, Search, X } from "lucide-react";
import { cards } from "@/lib/opsData";
import { useState } from "react";

export default function CardsPage(){
  const [selected,setSelected]=useState<(typeof cards)[number]|null>(null);
  return <main className="shell"><section className="page-head"><div><h1>Cards</h1><p>Search and audit every card detected in connected documents</p></div><button className="button"><Filter/> More filters</button></section>
  <section className="panel"><div className="panel-head"><div><h2>Card database</h2><p>{cards.length} sample records · 1,024 total cards</p></div><div className="panel-tools"><label className="input-wrap"><Search/><input aria-label="Search card text or citations" placeholder="Search cards or citations..."/></label><select className="select"><option>All cutters</option><option>Pingkang Qian</option><option>Tony Dong</option></select><select className="select"><option>All statuses</option><option>Verified</option><option>Exact duplicate</option><option>Near duplicate</option><option>Under review</option></select></div></div>
  <div className="table-scroll"><table><thead><tr><th>CARD PREVIEW</th><th>CUTTER</th><th>CITATION</th><th>SOURCE DOCUMENT</th><th>FIRST OBSERVED</th><th>SIMILARITY</th><th>STATUS</th></tr></thead><tbody>{cards.map(card=><tr key={card.id} onClick={()=>setSelected(card)} className="selectable-row"><td><strong>{card.title}</strong><small className="cell-meta">{card.id}</small></td><td>{card.cutter}<small className="cell-meta">{`// [${card.tag}]`}</small></td><td>{card.citation}</td><td>{card.document}</td><td>{card.date}</td><td>{card.similarity}</td><td><span className={`badge ${card.status==="Verified"?"verified":card.status==="Near duplicate"?"near":"exact"}`}><i/>{card.status}</span></td></tr>)}</tbody></table></div><div className="pagination"><span>Showing 1–5 of 1,024 cards</span><div><button>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></div></div></section>
  {selected&&<><button className="drawer-scrim" onClick={()=>setSelected(null)} aria-label="Close card details"/><aside className="card-drawer" aria-label="Card details"><header><div><small>{selected.id}</small><h2>Card details</h2></div><button onClick={()=>setSelected(null)} aria-label="Close card details"><X/></button></header><div className="drawer-body"><span className={`badge ${selected.status==="Verified"?"verified":"near"}`}><i/>{selected.status}</span><h3>{selected.title}</h3><p className="evidence">Regional transmission investment remains the binding constraint on clean generation deployment. Coordinated federal planning reduces reliability risks while enabling new capacity across constrained regions.</p><dl><dt>Cutter</dt><dd>{selected.cutter} · {`// [${selected.tag}]`}</dd><dt>Citation</dt><dd>{selected.citation}</dd><dt>Source document</dt><dd>{selected.document}</dd><dt>First observed</dt><dd>{selected.date} at 3:42 PM</dd><dt>Exact hash</dt><dd><code>87bd2f…9a31</code></dd><dt>Similarity group</dt><dd>{selected.similarity}</dd><dt>Decision reason</dt><dd>{selected.status==="Verified"?"Unique evidence with an approved cutter tag.":"Similar evidence requires administrator review."}</dd></dl><button className="button"><ExternalLink/> Open in Google Drive</button></div><footer><button className="button danger">Reject</button><button className="button">Reassign cutter</button><button className="button primary">Approve</button></footer></aside></>}
  </main>
}
