"use client";
import { Check, ExternalLink, RefreshCw } from "lucide-react";
import { useState } from "react";

const sections=["Google Drive","Card parsing","Duplicate detection","Anomaly detection","Leaderboard","Privacy"];
export default function SettingsPage(){
 const [section,setSection]=useState("Google Drive");
 return <main className="shell"><section className="page-head"><div><h1>Settings</h1><p>Configure data sources, parsing, scoring, and privacy</p></div><button className="button primary"><Check/> Save changes</button></section>
 <div className="settings-layout"><nav className="settings-menu" aria-label="Settings sections">{sections.map(item=><button className={section===item?"active":""} onClick={()=>setSection(item)} key={item}>{item}</button>)}</nav>
 <section className="panel">
  {section==="Google Drive"&&<><div className="settings-section"><h2>Google Drive connection</h2><p>PLT has read-only access to the selected preparation folder and its subfolders.</p><div className="connection-card"><span className="avatar">PQ</span><div><strong>qianpingkang@gmail.com</strong><small>Connected · Drive synced 2 minutes ago</small></div><span className="badge verified"><i/> Connected</span></div></div><div className="settings-section"><div className="form-grid"><label className="form-control"><span>Connected folder</span><input className="input" value="PLT Nationals 2026" readOnly/><small>Google Drive folder ID: 1AbC...xyz</small></label><label className="form-control"><span>Supported file types</span><select className="select"><option>Google Docs only</option></select></label></div><div className="settings-actions"><button className="button"><RefreshCw/> Reconnect Drive</button><button className="button"><ExternalLink/> Open folder</button><button className="button danger">Disconnect</button></div></div></>}
  {section==="Card parsing"&&<><div className="settings-section"><h2>Cutter-tag rules</h2><p>Tags are recognized only on their own line.</p><div className="form-grid"><label className="form-control"><span>Tag format</span><input className="input" value="// [username]" readOnly/><small>Example: // [pingkang]</small></label><label className="form-control"><span>Card boundary</span><select className="select"><option>Next cutter tag</option></select></label><label className="form-control"><span>Minimum card length</span><input className="input" type="number" defaultValue="25"/></label><label className="form-control"><span>Citation requirement</span><select className="select"><option>Recommended, not required</option><option>Required</option></select></label></div></div><div className="settings-section"><div className="toggle-row"><div><strong>Quarantine unknown tags</strong><p>Do not count tags until an administrator maps them.</p></div><button className="toggle on" aria-label="Quarantine unknown tags enabled"><i/></button></div></div></>}
  {section==="Duplicate detection"&&<div className="settings-section"><h2>Duplicate policy</h2><p>Exact and near duplicates are reviewed before leaderboard credit changes.</p><div className="form-grid"><label className="form-control"><span>Exact-match handling</span><select className="select"><option>Send for administrator review</option></select></label><label className="form-control"><span>Credit policy</span><select className="select"><option>Administrator review</option></select></label><label className="form-control"><span>Automatic duplicate threshold</span><input className="input" value="92%" readOnly/></label><label className="form-control"><span>Manual-review threshold</span><input className="input" value="80–92%" readOnly/></label></div></div>}
  {section==="Anomaly detection"&&<div className="settings-section"><h2>Anomaly detection</h2><p>Flag unusual behavior without making claims about intent.</p><div className="toggle-row"><div><strong>Burst activity monitoring</strong><p>Compare additions with team and member history.</p></div><button className="toggle on"><i/></button></div><div className="toggle-row"><div><strong>Temporarily exclude high-risk cards</strong><p>Hold cards outside the verified score until reviewed.</p></div><button className="toggle on"><i/></button></div><label className="form-control" style={{marginTop:18}}><span>Flagging sensitivity</span><select className="select"><option>Balanced</option><option>More sensitive</option><option>Less sensitive</option></select></label></div>}
  {section==="Leaderboard"&&<div className="settings-section"><h2>Leaderboard defaults</h2><p>Choose the initial period and metrics visible to the team.</p><div className="form-grid"><label className="form-control"><span>Default period</span><select className="select"><option>Current prep cycle</option></select></label><label className="form-control"><span>Ranking metric</span><select className="select"><option>Verified unique cards</option></select></label></div><div className="toggle-row"><div><strong>Show raw card counts</strong><p>Allow members to compare detected and verified totals.</p></div><button className="toggle on"><i/></button></div></div>}
  {section==="Privacy"&&<div className="settings-section"><h2>Document data</h2><p>Control how much extracted source content is retained.</p><div className="form-grid"><label className="form-control"><span>Card storage</span><select className="select"><option>Text, citations, and source metadata</option><option>Preview only</option></select></label><label className="form-control"><span>Retention period</span><select className="select"><option>While Drive is connected</option><option>One year</option></select></label></div><div className="settings-actions"><button className="button danger">Delete imported data</button></div></div>}
 </section></div></main>
}
